feature_name: Advertisement
properties:
  - key: com.openexchange.advertisement.<reseller>.packageScheme
    description: |
      Defines which package scheme is used for the reseller. <reseller> can be replaced with either the reseller name or the reseller id.
      Use 'OX_ALL' for the default reseller. Available package schemes are:
      Global - always uses the default reseller and default package.
      AccessCombinations - Using access combination names to retrive the package.
      TaxonomyTypes - Using taxonomy types to retrieve the package.
    defaultValue: Global
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: advertisement.properties
    tags: ["Advertisement"]
  - key: com.openexchange.advertisement.<reseller>.taxonomy.types
    description: |
      Defines a comma separated list of taxonomy types which are used as package identifiers. 
      This list is used by the 'TaxonomyTypes' package scheme to identify the package.
    defaultValue: 
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: advertisement.properties
    tags: ["Advertisement"]