feature_name: Calendar
properties:
    - key: com.openexchange.calendar.schedjoules.enabled
      description: |
        Configures if the <i>schedjoules</i> calendar provider is available for a user or not. 
      defaultValue: true
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe"]
    - key: com.openexchange.calendar.schedjoules.maxAccounts
      description: |
        Defines the maximum number of allowed accounts or subscriptions for a user within the <i>schedjoules</i> calendar provider. A value of <code>0</code> disables the limit.
      defaultValue: 20
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe","Limit"]
    - key: com.openexchange.calendar.ical.enabled
      description: |
        Configures if the <i>ical</i> calendar provider is available for a user or not. 
      defaultValue: true
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe"]
    - key: com.openexchange.calendar.ical.maxAccounts
      description: |
        Defines the maximum number of allowed accounts or subscriptions for a user within the <i>ical</i> calendar provider. A value of <code>0</code> disables the limit.
      defaultValue: 20
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe","Limit"]
    - key: com.openexchange.calendar.google.enabled
      description: |
        Configures if the <i>google</i> calendar provider is available for a user or not. 
      defaultValue: true
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe"]
    - key: com.openexchange.calendar.google.maxAccounts
      description: |
        Defines the maximum number of allowed accounts or subscriptions for a user within the <i>google</i> calendar provider. A value of <code>0</code> disables the limit.
      defaultValue: 20
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related:
      file: subscribe.properties
      packageName: open-xchange-subscribe
      tags: ["Calendar","Subscribe","Limit"]
    - key: com.openexchange.calendar.maxEventResults
      description: |
        Defines a maximum number of event in event results. The intention of this limit is to prevent out of memory situations.
      defaultValue: 1000
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.maxAttendeesPerEvent
      description: |
        Defines a maximum number of attendees per event. The intention of this limit is to prevent out of memory situations.
      defaultValue: 1000
      version: 7.10.0
      reloadable: false
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.maxAlarmsPerEvent
      description: |
        Defines a maximum number of alarms per event. The intention of this limit is to prevent out of memory situations.
      defaultValue: 100
      version: 7.10.0
      reloadable: false
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.provider.google.refreshInterval
      description: |
        Defines the refresh interval in minutes for the google calendar provider.
        If the value is < 0 the default of one day will be used.
      defaultValue: 10
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Google"]
    - key: com.openexchange.calendar.provider.google.retryOnErrorInterval
      description: |
        Defines the time in seconds to wait for the next request to google in case an error occurred.
        The minimum is 2 seconds.
      defaultValue: 1800
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Google"]
    - key: com.openexchange.calendar.migration.batchSize
      description: |
        Configures the batch size used when performing the update task com.openexchange.chronos.storage.rdb.migration.ChronosStorageMigrationTask. 
      defaultValue: 500
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Database"]
    - key: com.openexchange.calendar.migration.maxTombstoneAgeInMonths
      description: |
        Configures the maximum age of 'tombstone' calendar data that is considered when performing the update task com.openexchange.chronos.storage.rdb.migration.ChronosStorageMigrationTask. 
      defaultValue: 12
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Database"]
    - key: com.openexchange.calendar.useLegacyStorage
      description: |
        Forcibly re-enables usage of the 'legacy' tables for the calendar storage. 
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Database"]
    - key: com.openexchange.calendar.replayToLegacyStorage
      description: |
        Enables or disables the 'replaying' mode for the calendar storage that is entered automatically after migration. 
      defaultValue: true
      version: 7.10.0
      reloadable: true
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Database"]
    - key: com.openexchange.calendar.migration.purgeLegacyData
      description: |
        Manually activates an update task for purging legacy data after the calendar migration took place.  
      defaultValue: false
      version: 7.10.0
      reloadable: false
      configcascadeAware: false
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Database"]
    - key: com.openexchange.calendar.resolveGroupAttendees
      description: |
         Defines whether newly added group attendees should be resolved to their individual members implicitly, without preserving the group reference, or not. 
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Group"]
    - key: com.openexchange.calendar.maxConflictsPerRecurrence
      description: |
         Defines the maximum number of calculated conflicts between two recurring event series. 
      defaultValue: 5
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.maxAttendeesPerConflict
      description: |
         Defines the maximum number of attendees to indicate per conflict. 
      defaultValue: 5
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.maxConflicts
      description: |
         Configures the overall maximum number of conflicts to return. 
      defaultValue: 100
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar","Limit"]
    - key: com.openexchange.calendar.skipExternalAttendeeURIChecks
      description: |
         Controls whether checks of (external) attendee URIs are disabled or not. 
      defaultValue: false
      version: 7.10.0
      reloadable: true
      configcascadeAware: true
      related: 
      file: calendar.properties
      packageName: open-xchange-core
      tags: ["Calendar"]
