feature_name: Folder
properties:
  - key: com.openexchange.folderstorage.defaultPermissions
    description: |
      Specifies default permission to use in case folder is supposed to be created below a certain parent folder.
      The value is a pipe ("&#124;") separated listing of expressions; each expression defines the default permissions
      for a denoted parent folder. Currently the reserved folder identifiers "2" and "15" are considered as "2"
      denoted the public PIM folder whereas "15" denotes the public Drive folder.

      An expression starts with the parent folder identifier followed by '=' character; e.g. "2=".
      Then there is a comma-separated list of permissions to assume per entity (user or group).

      Each permission either starts with "user_", "admin_user_", "group_" or "admin_group_" (the prefix "admin_" controls
      whether the entity is supposed to be set as folder administrator) followed by the numeric entity identifier.

      Then an '@' character is supposed to occur and finally followed by rights expression. The rights may be dot-separated
      listing (<folder-permission> + "." + <read-permission> + "." + <write-permission> + "." + <delete-permission>) or one
      of the tokens  "viewer", "writer" or "author".

      More formally
      expressions = expression ("&#124;" expression)*
      expression = folder "=" permission ("," permission)*
      permission = ("admin_")? ("group_" &#124; "user_") entity(int) "@" rights
      rights = (folder-permission(int) "." read-permission(int) "." write-permission(int) "." delete-permission(int)) &#124; ("viewer" &#124; "writer" &#124; "author")

      Example
      2=group_2@2.4.0.0,admin_user_5@8.4.4.4&#124;15=admin_group_2@8.8.8.8
      2=group_2@viewer,admin_user_5@author&#124;15=admin_group_2@writer
    defaultValue:
    version: 7.8.4
    reloadable: true
    configcascadeAware: true
    related: 
    file: foldercache.properties
    tags: ["Folder"]
  - key: com.openexchange.folderstorage.inheritParentPermissions
    description: |
        Specifies if permissions of new parent folder should be applied when moving a folder into the public folder tree.
    defaultValue: false
    version: 7.8.4
    reloadable: false
    configcascadeAware: false
    related: 
    file: foldercache.properties
    tags: ["Folder"]