feature_name: PushNotificationService
properties:
  - key: com.openexchange.pns.delayDuration
    description: |
      The time in milliseconds a notification is queued in buffer to possible aggregate
      with similar notifications that arrive during that time
    defaultValue: 1000
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.timerFrequency
    description: |
      The frequency/delay in milliseconds when the buffering queue will be checked for due
      notifications (the ones exceeding delayDuration in queue)
    defaultValue: 500
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.numProcessorThreads
    description: |
      Specifies the number of threads that concurrently handle due notifications that were transferred
      from buffering queue to processing queue.
    defaultValue: 500
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.maxProcessorTasks
    description: |
      Specifies the buffer size for due notifications that were transferred from buffering queue to
      processing queue.
    defaultValue: 65536
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.transport.apn.ios.enabled
    description: |
      Specifies whether the APNS transport is enabled. That property is responsive to config-cascade
      and reloadable as well.

      Moreover, an even finer-grained decision is possible to be configured as a certain transport
      is checked for availability providing user, context, client and topic.
      Hence, it is possible to  specify:

      com.openexchange.pns.transport.apn.ios.enabled + ("." + {client})? + ("." + {topic})?

      com.openexchange.pns.transport.apn.ios.enabled.open-xchange-appsuite.ox:mail:new=true
      com.openexchange.pns.transport.apn.ios.enabled.open-xchange-appsuite.ox:calendar:new=false

      That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
      via APNS, but not for "new appointment".
    defaultValue: false
    version: 7.8.3
    reloadable: true
    configcascadeAware: true
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.transport.apn.ios.feedbackQueryInterval
    description: |
      Specifies the frequency in milliseconds when to query the Apple feedback service to check for expired
      and/or invalid tokens.
    defaultValue: 3600000
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.transport.gcm.enabled
    description: |
      Specifies whether the GCM transport is enabled. That property is responsive to config-cascade
      and reloadable as well.

      Moreover, an even finer-grained decision is possible to be configured as a certain transport
      is checked for availability providing user, context, client and topic.
      Hence, it is possible to  specify:

      com.openexchange.pns.transport.gcm.enabled + ("." + {client})? + ("." + {topic})?

      com.openexchange.pns.transport.gcm.enabled.open-xchange-appsuite.ox:mail:new=true
      com.openexchange.pns.transport.gcm.enabled.open-xchange-appsuite.ox:calendar:new=false

      That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
      via GCM, but not for "new appointment".
    defaultValue: false
    version: 7.8.3
    reloadable: true
    configcascadeAware: true
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.transport.wns.enabled
    description: |
      Specifies whether the WNS transport is enabled. That property is responsive to config-cascade
      and reloadable as well.

      Moreover, an even finer-grained decision is possible to be configured as a certain transport
      is checked for availability providing user, context, client and topic.
      Hence, it is possible to  specify:

      com.openexchange.pns.transport.wns.enabled + ("." + {client})? + ("." + {topic})?

      com.openexchange.pns.transport.wns.enabled.open-xchange-appsuite.ox:mail:new=true
      com.openexchange.pns.transport.wns.enabled.open-xchange-appsuite.ox:calendar:new=false

      That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
      via WNS, but not for "new appointment".
    defaultValue: false
    version: 7.8.3
    reloadable: true
    configcascadeAware: true
    related:
    file: pns.properties
    tags: ["PushNotificationService"]
  - key: com.openexchange.pns.transport.websocket.enabled
    description: |
      Specifies whether the Web Socket transport is enabled. That property is responsive to config-cascade
      and reloadable as well.

      Moreover, an even finer-grained decision is possible to be configured as a certain transport
      is checked for availability providing user, context, client and topic.
      Hence, it is possible to  specify:

      com.openexchange.pns.transport.websocket.enabled + ("." + {client})? + ("." + {topic})?

      com.openexchange.pns.transport.websocket.enabled.open-xchange-appsuite.ox:mail:new=true
      com.openexchange.pns.transport.websocket.enabled.open-xchange-appsuite.ox:calendar:new=false

      That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
      via Web Socket, but not for "new appointment".
    defaultValue: true
    version: 7.8.3
    reloadable: true
    configcascadeAware: true
    related: com.openexchange.websockets.enabled
    file: pns.properties
    tags: ["PushNotificationService"]
