feature_name: Report
properties:
  - key: com.openexchange.report.appsuite.fileStorage
    description: |
      Reports filestorage directory for storage of report parts and composed data.
    defaultValue: /tmp
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    tags: ["Report"]
  - key: com.openexchange.report.appsuite.maxChunkSize
    description: |
      Determines how many chunks of data can be kept in the report before saving them in the folder described in the 
      com.openexchange.report.client.fileStorage property
    defaultValue: 200
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    tags: ["Report"]
  - key: com.openexchange.report.appsuite.maxThreadPoolSize
    description: |
      Number of threads allowed to work on the report at the same time.
    defaultValue: 20
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    tags: ["Report"]
  - key: com.openexchange.report.appsuite.threadPriority
    description: |
      The priority that threads, working on the report have. Allowed value range is 1-10. 1 is the lowest, 10 the highest priority.
    defaultValue: 1
    version: 7.8.3
    reloadable: true
    configcascadeAware: false
    related: 
    file: reportserialization.properties
    tags: ["Report"]               