/mailfilter?action=config:
  get:
    operationId: getConfig
    tags:
      - mailfilter
    summary: Gets the configuration of the mail filter backend.
    description: |
      A mail filter can have different rules each containing one command. A command has a test condition and actions
      that are executed if the condition is true. The list of available comparisions (that can be used in test
      conditions) and the list of available actions depends on a given test and the mail filter server configuration
      and must be determined at runtime.
      
      All those dynamic values can be fetched via a config object at startup, which shows the capabilities of the server
      to the client.
    parameters:
      - $ref: "#/parameters/gblQueryParamSession"
      - in: query
        name: username
        type: string
        description: Must contain the user name for **admin mode**. So the normal credentials are taken for authentication but the mail filter of the user with this username is being changed.
        required: false
    responses:
      200:
        description: |
          A JSON object with the fields `tests` (containing an array of available test-objects, see [Possible tests](https://documentation.open-xchange.com/latest/middleware/http_api/4_mail_filter.html#possible-tests) too) and `actioncommands`
          (containing an array of [valid actions](#possible-action-commands)). In case of errors the responsible fields in the response are
          filled (see [Error handling](#error-handling)).
        schema:
          $ref: "#/definitions/MailFilterConfigResponse"