# If you want to override values here
# Use the as-config.yml. This file will be overwritten
default:
    pageTitle: 'App Suite. '

    pageHeaderPrefix: 'OX'
    pageHeader: 'App Suite'

    productName: 'OX App Suite'
    productNameMail: 'OX Mail'

    contact: 'Open-Xchange AG, Rollnerstr. 14, D-90408 NÃ¼rnberg, E-Mail: info@open-xchange.com'

    forgotPassword: false

    copyright: '(c) 2014 Open-Xchange.'

    staySignedIn: true
    