array:
  - data:
      Key: com.openexchange.dovecot.doveadm.endpoints
      Description: >
Specifies the URIs to the Dovecot DoveAdm REST interface end-points. 
e.g. "http://dovecot1.host.invalid:8081, http://dovecot2.host.invalid:8081, http://dovecot3.host.invalid:8081"

Moreover connection-related attributes are allowed to be specified to influence HTTP connection and pooling behavior
com.openexchange.mailaccount.dovecot.endpoints.totalConnections        The number of total connections held in HTTP connection pool
com.openexchange.mailaccount.dovecot.endpoints.maxConnectionsPerRoute  The number of connections per route held in HTTP connection pool; or less than/equal to 0 (zero) for auto-determining
com.openexchange.mailaccount.dovecot.endpoints.readTimeout             The read time-out in milliseconds
com.openexchange.mailaccount.dovecot.endpoints.connectTimeout          The connect time-out in milliseconds

Full example :
com.openexchange.mailaccount.dovecot.endpoints=http://dovecot1.host.invalid:8081, http://dovecot2.host.invalid:8081
com.openexchange.mailaccount.dovecot.endpoints.totalConnections=100
com.openexchange.mailaccount.dovecot.endpoints.maxConnectionsPerRoute=0 (max. connections per route is then determined automatically by specified end-points)
com.openexchange.mailaccount.dovecot.endpoints.readTimeout=2500
com.openexchange.mailaccount.dovecot.endpoints.connectTimeout=1500

Default is empty
The values can be configured within a dedicated .properties file; e.g. 'doveadm.properties'.
      Default: 
      Version: 7.8.3
      Reloadable: false
      Configcascade_Aware: false
      Related: 
      File: doveadm.properties
  - data:
      Key: com.openexchange.dovecot.doveadm.apiSecret
      Description: >
Specifies the API secret to communicate with the Dovecot DoveAdm REST interface

Default is empty
      Default: 
      Version: 7.8.3
      Reloadable: false
      Configcascade_Aware: false
      Related: 
      File: doveadm.properties
  		