array:
  - data:
      Key: `com.openexchange.pns.delayDuration`
      Description: >
The time in milliseconds a notification is queued in buffer to possible aggregate
with similar notifications that arrive during that time
Default 1000
      Default: 1000
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: false
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.timerFrequency`
      Description: >
The frequency/delay in milliseconds when the buffering queue will be checked for due
notifications (the ones exceeding delayDuration in queue)
Default 500
      Default: 500
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: false
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.numProcessorThreads`
      Description: >
Specifies the number of threads that concurrently handle due notifications that were transferred
from buffering queue to processing queue.
Default 10
      Default: 500
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: false
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.maxProcessorTasks`
      Description: >
Specifies the buffer size for due notifications that were transferred from buffering queue to
processing queue.
Default 65536
      Default: 65536
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: false
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.transport.apn.ios.enabled`
      Description: >
Specifies whether the APNS transport is enabled. That property is responsive to config-cascade
and reloadable as well.

Moreover, an even finer-grained decision is possible to be configured as a certain transport
is checked for availability providing user, context, client and topic.
Hence, it is possible to  specify:

com.openexchange.pns.transport.apn.ios.enabled + ("." + {client})? + ("." + {topic})?

com.openexchange.pns.transport.apn.ios.enabled.open-xchange-appsuite.ox:mail:new=true
com.openexchange.pns.transport.apn.ios.enabled.open-xchange-appsuite.ox:calendar:new=false

That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
via APNS, but not for "new appointment".

Default false
      Default: false
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: true
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.transport.apn.ios.feedbackQueryInterval`
      Description: >
Specifies the frequency in milliseconds when to query the Apple feedback service to check for expired
and/or invalid tokens.
Default 3600000 (1 hour)
      Default: 3600000
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: false
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.transport.gcm.enabled`
      Description: >
Specifies whether the GCM transport is enabled. That property is responsive to config-cascade
and reloadable as well.

Moreover, an even finer-grained decision is possible to be configured as a certain transport
is checked for availability providing user, context, client and topic.
Hence, it is possible to  specify:

com.openexchange.pns.transport.gcm.enabled + ("." + {client})? + ("." + {topic})?

com.openexchange.pns.transport.gcm.enabled.open-xchange-appsuite.ox:mail:new=true
com.openexchange.pns.transport.gcm.enabled.open-xchange-appsuite.ox:calendar:new=false

That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
via GCM, but not for "new appointment".

Default false
      Default: false
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: true
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.transport.wns.enabled`
      Description: >
Specifies whether the WNS transport is enabled. That property is responsive to config-cascade
and reloadable as well.

Moreover, an even finer-grained decision is possible to be configured as a certain transport
is checked for availability providing user, context, client and topic.
Hence, it is possible to  specify:

com.openexchange.pns.transport.wns.enabled + ("." + {client})? + ("." + {topic})?

com.openexchange.pns.transport.wns.enabled.open-xchange-appsuite.ox:mail:new=true
com.openexchange.pns.transport.wns.enabled.open-xchange-appsuite.ox:calendar:new=false

That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
via WNS, but not for "new appointment".

Default false
      Default: false
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: true
      Related:
      File: pns.properties
  - data:
      Key: `com.openexchange.pns.transport.websocket.enabled`
      Description: >
Specifies whether the Web Socket transport is enabled. That property is responsive to config-cascade
and reloadable as well.

Moreover, an even finer-grained decision is possible to be configured as a certain transport
is checked for availability providing user, context, client and topic.
Hence, it is possible to  specify:

com.openexchange.pns.transport.websocket.enabled + ("." + {client})? + ("." + {topic})?

com.openexchange.pns.transport.websocket.enabled.open-xchange-appsuite.ox:mail:new=true
com.openexchange.pns.transport.websocket.enabled.open-xchange-appsuite.ox:calendar:new=false

That allows the client "open-xchange-appsuite" (App Suite UI) to receive "new mail" notifications
via Web Socket, but not for "new appointment".

Default false
      Default: false
      Version: 7.8.3
      Reloadable: true
      Configcascade_Aware: true
      Related: com.openexchange.websockets.enabled
      File: pns.properties
