/tasks?action=list:
  put:
    operationId: getTaskList
    tags:
      - Tasks
    summary: Gets a list of tasks.
    parameters:
      - $ref: '#/components/parameters/gblQueryParamSession'
      - $ref: '#/components/parameters/gblQueryParamTaskColumns'
    responses:
      '200':
        description: >
          A JSON object containing an array with data for the requested tasks.
          Each array element describes one task and

          is itself an array. The elements of each array contain the information
          specified by the corresponding

          identifiers in the `columns` parameter. In case of errors the
          responsible fields in the response are

          filled (see [Error handling](#error-handling)).
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TasksResponse'
    requestBody:
      $ref: '#/components/requestBodies/TaskListElementArray'
