/tasks?action=new:
  put:
    operationId: createTask
    tags:
      - Tasks
    summary: Creates a task.
    parameters:
      - $ref: '#/components/parameters/gblQueryParamSession'
    responses:
      '200':
        description: >
          A JSON object containing the id of the newly created task. In case of
          errors the responsible fields in the response are

          filled (see [Error handling](#error-handling)).
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateResponse'
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskData'
      description: A JSON object containing the task's data.
      required: true
