type: object
properties:
  confirmation:
    type: integer
    description: '0 (none), 1 (accepted), 2 (declined), 3 (tentative).'
  confirmmessage:
    type: string
    description: The confirmation message or comment.